version: '3.3'
services:

    vsc-server:
        build: .
        container_name: vsc-server
        hostname: vsc-server
        networks:
            vsc-net:
        volumes:
            - /home/robert/.config/:/home/coder/.config/        
            - /home/robert/.m2/settings.xml:/home/coder/.m2/settings.xml
            - /home/robert/:/home/coder/project/
            #add socket required for docker
            - /var/run/docker.sock:/var/run/docker.sock       
        environment:
            - DOCKER_USER=$USER
        user: "${EXAMPLE_UID}:${EXAMPLE_GID}"
        expose:
            - 8080
        ports:
            - 9001:8080    

networks:
    vsc-net:
